In [2]:
import numpy as np;
import matplotlib.pyplot as plt;
rand=np.random.rand;

In [3]:

test_in=np.genfromtxt("test_in.csv", delimiter=',');
test_out=np.genfromtxt("test_out.csv", delimiter=',');
train_in=np.genfromtxt("train_in.csv", delimiter=',');
train_out=np.genfromtxt("train_out.csv", delimiter=',');

In [4]:
NUM_TRAIN=len(train_out);
NUM_TEST=len(test_out);

c_train=np.zeros(50);
c_test=np.zeros(50);

In [6]:
NUM_TEST

1000

In [14]:
x=train_in[0]

In [15]:
w=np.random.rand(10,256)

In [20]:
(w*x).shape

(10, 256)

In [51]:
x = np.arange(5)

In [63]:
w = np.arange(50).reshape(10,5)

In [34]:
print(w,w*x,)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]] [[ 0  1  4]
 [ 0  4 10]
 [ 0  7 16]
 [ 0 10 22]
 [ 0 13 28]] [ 5 14 23 32 41]


In [36]:
a=np.sum(w*x,axis=1)

In [54]:
print(x)

[0 1 2 3 4]


In [64]:
x*w

array([[  0,   1,   4,   9,  16],
       [  0,   6,  14,  24,  36],
       [  0,  11,  24,  39,  56],
       [  0,  16,  34,  54,  76],
       [  0,  21,  44,  69,  96],
       [  0,  26,  54,  84, 116],
       [  0,  31,  64,  99, 136],
       [  0,  36,  74, 114, 156],
       [  0,  41,  84, 129, 176],
       [  0,  46,  94, 144, 196]])

In [65]:
np.dot(x,w.T)

array([ 30,  80, 130, 180, 230, 280, 330, 380, 430, 480])

In [66]:
np.sum(x*w,axis=1)

array([ 30,  80, 130, 180, 230, 280, 330, 380, 430, 480])

In [77]:
import numpy as np;
import matplotlib.pyplot as plt;

rand=np.random.rand;

test_in=np.genfromtxt("test_in.csv", delimiter=',');
test_out=np.genfromtxt("test_out.csv", delimiter=',');
train_in=np.genfromtxt("train_in.csv", delimiter=',');
train_out=np.genfromtxt("train_out.csv", delimiter=',');

NUM_TRAIN=len(train_out);
NUM_TEST=len(test_out);

c_train=np.zeros(20);
c_test=np.zeros(20);
knopen = 10

rate=5;
for epochs in range(1, 21):
	print(epochs);
	w=rand(9, 256);
	w_b=rand(9);

	y=np.zeros(10);

	#epochs=100;
	for i in range(0, epochs):
		for j in range(0, NUM_TRAIN):
			x=train_in[j];
			c=np.int(train_out[j]);
			
			a=w_b+np.sum(w*x, axis=1);
			y=2*(a>=0)-1;
			
			for k in range(0, 9):
				delta=2*(k==c)-1-y[k];
				if delta!=0:
					w[k]=w[k]+rate*delta*x;
					w_b[k]=w_b[k]+rate*delta;

	correct_train=0;
	for i in range(0, NUM_TRAIN):
		x=train_in[i];
		c=np.int(train_out[i]);
		a=w_b+np.sum(w*x, axis=1);
		#y=2*(a>=0)-1;
		if(np.argmax(a)==c):
			correct_train=correct_train+1;
	c_train[epochs-1]=correct_train;

	correct_test=0;
	for i in range(0, NUM_TEST):
		x=test_in[i];
		c=np.int(test_out[i]);
		a=w_b+np.sum(w*x, axis=1);
		#y=2*(a>=0)-1;
		if(np.argmax(a)==c):
			correct_test=correct_test+1;
	c_test[epochs-1]=correct_test;


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [78]:
plt.plot(c_train/1707)
plt.plot(c_test/1000)
plt.ylim([0,1])
plt.show()